# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required

apt_packages:
    - gsl-bin
    - libgsl0-dbg
    - libgsl0-dev
    - libgsl0ldbl

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change